@ECHO OFF

SET LIBRARY_ROOT=%~dp0
ECHO LIBRARY_ROOT: %LIBRARY_ROOT%

SET KISO_MAYA_PATH=%LIBRARY_ROOT%Maya
SET KISO_MAYA_PYTHON_PATH=%LIBRARY_ROOT%Python\kiso
ECHO KISO_MAYA_PYTHON_PATH: %KISO_MAYA_PYTHON_PATH%
SET KISO_MAYA_SCRIPT_PATH=%KISO_MAYA_PATH%\Scripts
SET KISO_MAYA_PLUG_IN_PATH=%KISO_MAYA_PATH%\Plugins2016_Win
SET KISO_XBMLANGPATH=%KISO_MAYA_PATH%\Icons

REM SET PYTHONPATH=%PYTHONPATH%;%KISO_MAYA_PYTHON_PATH%

SET MAYA_MODULE_PATH=%MAYA_MODULE_PATH%;%LIBRARY_ROOT%Maya
ECHO %MAYA_MODULE_PATH%
REM SET MAYA_SCRIPT_PATH=%MAYA_SCRIPT_PATH%;%KISO_MAYA_SCRIPT_PATH%;%KISO_MAYA_PYTHON_PATH%
REM SET MAYA_SCRIPT_PATH=%MAYA_SCRIPT_PATH%;%KISO_MAYA_PYTHON_PATH%
SET MAYA_SCRIPT_PATH=%MAYA_SCRIPT_PATH%;%KISO_MAYA_SCRIPT_PATH%;%KISO_MAYA_PYTHON_PATH%
SET MAYA_PLUG_IN_PATH=%MAYA_PLUG_IN_PATH%;%KISO_MAYA_PLUG_IN_PATH%
SET XBMLANGPATH=%XBMLANGPATH%;%KISO_XBMLANGPATH%

FOR /F "tokens=2* skip=2" %%A IN ('REG QUERY "HKLM\SOFTWARE\Autodesk\Maya\2016\Setup\InstallPath" /reg:64 /v MAYA_INSTALL_LOCATION') DO SET MAYA2016_LOCATION=%%B
ECHO MAYA2016_LOCATION=%MAYA2016_LOCATION%

"%MAYA2016_LOCATION%bin\maya.exe"
REM pause