#!/bin/bash
set -e

cd "`dirname "$0"`"
LIBRARY_ROOT="`dirname "$0"`"
export LIBRARY_ROOT
echo LIBRARY_ROOT: $LIBRARY_ROOT

KISO_MAYA_PATH=$LIBRARY_ROOT/Maya
export KISO_MAYA_PATH
echo KISO_MAYA_PATH: $KISO_MAYA_PATH

KISO_MAYA_SCRIPT_PATH=$KISO_MAYA_PATH/Scripts
export KISO_MAYA_SCRIPT_PATH
echo KISO_MAYA_SCRIPT_PATH: $KISO_MAYA_SCRIPT_PATH

KISO_MAYA_PLUG_IN_PATH=$KISO_MAYA_PATH/Plugins2015_OSX
export KISO_MAYA_PLUG_IN_PATH
echo KISO_MAYA_PLUG_IN_PATH: $KISO_MAYA_PLUG_IN_PATH

KISO_XBMLANGPATH=$KISO_MAYA_PATH/Icons
export KISO_XBMLANGPATH
echo KISO_XBMLANGPATH: $KISO_XBMLANGPATH

MAYA_SCRIPT_PATH=$MAYA_SCRIPT_PATH:$KISO_MAYA_SCRIPT_PATH
export MAYA_SCRIPT_PATH
MAYA_PLUG_IN_PATH=$MAYA_PLUG_IN_PATH:$KISO_MAYA_PLUG_IN_PATH
export MAYA_PLUG_IN_PATH
XBMLANGPATH=$XBMLANGPATH:$KISO_XBMLANGPATH
export XBMLANGPATH

MAYA_LOCATION=/Applications/Autodesk/maya2015/Maya.app/Contents
export MAYA_LOCATION

MAYA_EXE_PATH=$MAYA_LOCATION/MacOS
export MAYA_EXE_PATH

echo $MAYA_LOCATION
echo $MAYA_EXE_PATH

$MAYA_EXE_PATH/Maya