@ECHO OFF

FOR /F "tokens=2* skip=2" %%A IN ('REG QUERY "HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\11.0" /reg:64 /v InstallDir') DO SET VS_LOCATION=%%B
ECHO VS_LOCATION=%VS_LOCATION%

FOR /F "tokens=2* skip=2" %%A IN ('REG QUERY "HKLM\SOFTWARE\Autodesk\Maya\2016\Setup\InstallPath" /reg:64 /v MAYA_INSTALL_LOCATION') DO SET MAYA_LOCATION=%%B
ECHO MAYA_LOCATION=%MAYA_LOCATION%

SET MAYA_EXE=%MAYA_LOCATION%bin\maya.exe
SET MAYA_SDK_INCLUDE=%MAYA_LOCATION%include
SET MAYA_SDK_LIB=%MAYA_LOCATION%lib

"%VS_LOCATION%devenv.exe"
